#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_LOGOBAR                             104
#define PSP_PAGE_LOGIN                          115
#define PSP_PAGE_NEWPWD                         116
#define PSP_PAGE_CHALLENGE                      117
#define PSP_PAGE_RESPONSE                       118
#define PSP_PAGE_NEWKEY                         120
#define IDI_LOGO                                122
#define IDI_SYSTRAY_ACTIVE                      124
#define IDC_EDIT1                               1000
#define TB_KEYPWD                               1001
#define TB_RESPONSE                             1001
#define TX_NEWPWD                               1001
#define CK_CHGPWD                               1002
#define IDC_EDIT2                               1002
#define PB_IMPORTER                             1002
#define CK_IMPORTKEY                            1003
#define PB_ENREGISTRER                          1003
#define PB_IMPORTKEY                            1003
#define TB_KEYFILE                              1004
#define TB_PWD                                  1004
#define TB_CHALLENGE                            1005
#define PB_MAILTO                               1007
#define IDS_TITLE                               40000
#define IDS_TITLE_LOGIN                         40001
#define IDS_TITLE_CHGPWD                        40002
#define IDS_TITLE_NEWKEY                        40003
#define IDS_TITLE_CHALLENGE                     40004
#define IDS_TITLE_RESPONSE                      40005
#define IDS_CHGPWD                              40006
#define IDS_PASSWORD_POLICY_MESSAGE             40007
#define IDS_PWD1_PWD2                           40008
#define IDS_KEYSTORE_LOAD_ERROR                 40009
#define IDS_KEYSTORE_SAVE_ERROR                 40010
#define IDS_ERROR_BADPWD                        40011
#define IDS_ERROR_KEYEXISTS                     40012
#define IDS_ERROR_FILENOTFOUND                  40013
#define IDS_ERROR_FILEREAD                      40014
#define IDS_ERROR_FILEWRITE                     40015
#define IDS_ERROR_GENERIC                       40016
#define IDS_CONFIRM_KEY_IMPORTED                40017
#define IDS_CONFIRM_PWD_CHANGE                  40018
#define IDS_ERROR_CHALLENGE                     40019
#define IDS_ERROR_RESPONSE                      40020
#define IDS_CONFIRM_USER                        40021
#define IDS_ERROR_BADFILE                       40022
