#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDAPPLY                                 3
#define IDD_CHALLENGE                           101
#define IDD_RESPONSE                            102
#define IDB_LOGO_FONDBLANC                      103
#define IDD_LAUNCH_APP                          105
#define IDD_CHOOSE_CONFIG                       108
#define IDD_SELECT_DOMAIN                       110
#define PB_SAVEAS                               1000
#define PSP_ABOUT                               1000
#define TB_ID1                                  1000
#define TB_PWD_CLEAR                            1000
#define TX_SERVER1                              1000
#define CK_VISIBLE                              1001
#define IDC_SEP_INFORMATIONS                    1001
#define IDI_SYSTRAY_ACTIVE                      1001
#define LV_CONFIGS                              1001
#define TB_CHALLENGE                            1001
#define CK_ID1                                  1002
#define IDC_SEP_STATISTIQUES                    1002
#define IDI_SYSTRAY_INACTIVE                    1002
#define CB_DOMAINS                              1003
#define IDC_CURSOR_HAND                         1003
#define IDC_SEP_SECURITE                        1003
#define TB_LANCEMENT                            1003
#define IDC_SEP_AUTORISATIONS                   1004
#define IDI_LOUPE                               1004
#define TX_SERVER2                              1004
#define IDC_SEP_PROXY                           1005
#define TX_SERVER                               1005
#define IDC_SEP_LICENCE                         1006
#define IDD_PWD                                 1006
#define TX_LANCEMENT                            1006
#define IDD_CHANGE_PWD                          1007
#define TX_DOMAIN                               1007
#define CK_PWD                                  1008
#define PSP_INTERNET                            1008
#define CK_ID2                                  1009
#define IDD_ID_AND_PWD                          1009
#define CK_ID3                                  1010
#define IDD_APPNSITES                           1010
#define CK_ID4                                  1011
#define IDD_FORCE_CHANGE_PWD                    1011
#define IDB_TVIMAGES                            1012
#define IDD_MESSAGEBOX3B                        1013
#define IDD_SIMPLE_PWD_CHOICE                   1014
#define IDB_LOGO                                1016
#define IDB_LOUPE                               1017
#define PB_TEST                                 1019
#define TB_PWD1                                 1020
#define TB_TITRE                                1021
#define TX_CONFIGFILE                           1022
#define TB_ID                                   1024
#define TB_PWD2                                 1025
#define TX_PORTAL                               1026
#define TB_PWD                                  1027
#define TB_ID2                                  1028
#define TB_ID3                                  1029
#define TB_ID4                                  1030
#define TB_VALIDATION                           1031
#define TB_ID2_ID                               1034
#define TX_NBSSO                                1035
#define TB_ID3_ID                               1036
#define TX_STATISTIQUES                         1037
#define TB_ID4_ID                               1038
#define TX_NBAPP                                1039
#define TX_INFORMATIONS                         1041
#define TB_URL                                  1042
#define TX_PWDENCRYPTED                         1043
#define TX_URL                                  1044
#define IMG_LOUPE                               1047
#define TX_LICENCE                              1048
#define TX_PWD1                                 1049
#define TX_ABOUT                                1051
#define TX_PWD                                  1061
#define TX_ID                                   1062
#define TX_TITRE                                1063
#define TX_ID_ID                                1064
#define TX_PWD_ID                               1065
#define TX_VALIDATION                           1066
#define TX_TYPE                                 1067
#define CB_TYPE                                 1068
#define PB_OUVRIR                               1069
#define TX_ID2_TYPE                             1070
#define CB_ID2_TYPE                             1071
#define PB_PARCOURIR                            1072
#define PB_LICENCE                              1073
#define TB_OLD_PWD                              1074
#define TX_ID2_ID                               1075
#define CK_SAVE                                 1076
#define TB_NEW_PWD1                             1077
#define TX_ID3_ID                               1078
#define TB_NEW_PWD2                             1079
#define TX_ID4_ID                               1080
#define TX_PROXY                                1081
#define CK_GET_CONFIG                           1082
#define TX_ID3_TYPE                             1083
#define CB_ID3_TYPE                             1084
#define CK_USE_PROXY                            1085
#define TX_ID4_TYPE                             1086
#define TX_PROXY_URL                            1087
#define CB_ID4_TYPE                             1088
#define TB_PROXY_URL                            1089
#define TX_PROXY_USER                           1090
#define TX_PROXY_PWD                            1093
#define TB_PROXY_USER                           1094
#define TB_PROXY_PWD                            1096
#define TX_INTERNET                             1101
#define CK_CHECK_VERSION                        1102
#define TX_SECURITE                             1105
#define CK_LOCK                                 1106
#define CK_CHECK_BETA                           1108
#define PB_CHANCE                               1112
#define TX_ID2                                  1114
#define TX_ID3                                  1115
#define TX_ID4                                  1116
#define TV_APPLICATIONS                         1119
#define TX_PWD2                                 1120
#define TAB_APPLICATIONS                        1124
#define TAB_IDPWD                               1125
#define TAB_CONFIG                              1126
#define TB_ID_ID                                1127
#define TB_PWD_ID                               1128
#define TX_CONFIGFILE2                          1161
#define TX_PORTAL2                              1166
#define TX_FRAME                                1167
#define TX_SUBTITLE                             1168
#define PB_B1                                   1169
#define PB_B2                                   1170
#define TX_MESSAGE                              1171
#define STATIC_ICONE                            1172
#define TB_KBSIM                                1173
#define CK_KBSIM                                1174
#define IDC_SEPARATOR                           1175
#define IDI_LOGO                                1176
#define IDD_CHANGE_IDS                          1177
#define IDS_BADPWD                              40000
#define IDS_DEFAULT_PORTAL                      40001
#define IDS_COMBOTYPE1                          40002
#define IDS_COMBOTYPE2                          40003
#define IDS_COMBOTYPE3                          40004
#define IDS_OLDVERSION                          40005
#define IDS_PP_ENCRYPTED                        40006
#define IDS_DELETE                              40007
#define IDS_MENU_ACTIVER                        40008
#define IDS_MENU_AJOUTER_APPLI                  40009
#define IDS_MENU_SUPPRIMER                      40010
#define IDS_MENU_DESACTIVER                     40011
#define IDS_MENU_QUITTER                        40012
#define IDS_MENU_PROP                           40013
#define IDS_ACTIVE                              40014
#define IDS_DESACTIVE                           40015
#define IDS_MENU_MDP                            40016
#define IDS_CHANGE_PWD_FAILED                   40017
#define IDS_CHANGE_PWD_OK                       40018
#define IDS_MENU_PORTAL                         40019
#define IDS_MENU_THIS_APPLI                     40020
#define IDS_CONFIG_NOT_FOUND                    40021
#define IDS_NEW_VERSION                         40022
#define IDS_MENU_DEPLACER                       40023
#define IDS_CONFIG_ALREADY_EXISTS               40024
#define IDS_CONFIG_PROXY                        40025
#define IDS_MENU_APPNSITES                      40026
#define IDS_VALUE                               40027
#define IDS_MENU_RENOMMER                       40028
#define IDS_COMBOIDTYPE1                        40029
#define IDS_COMBOIDTYPE2                        40030
#define IDS_NON_CLASSE                          40031
#define IDS_NEW_CATEG                           40032
#define IDS_MENU_AJOUTER_CATEG                  40033
#define IDS_NEW_APP                             40034
#define IDS_APPNAME_ALREADY_EXISTS              40035
#define IDS_CATEGNAME_ALREADY_EXISTS            40036
#define IDS_CATEG_NOT_EMPTY                     40037
#define IDS_PASSWORD_POLICY_MESSAGE             40038
#define IDS_CATEG_NOT_REMOVABLE                 40039
#define IDS_FORCE_CHANGE                        40040
#define IDS_PWD_CHANGED_RECENTLY                40041
#define IDS_NEW_APP_PWD                         40042
#define IDS_CONFIG_EXISTS_SUBTITLE              40043
#define IDS_CONFIG_EXISTS_MESSAGE               40044
#define IDS_CONFIG_EXISTS_B1                    40045
#define IDS_CONFIG_EXISTS_B2                    40046
#define IDS_CONFIG_EXISTS_B3                    40047
#define IDS_DESACTIVATE_MESSAGE                 40048
#define IDS_MESSAGEBOX_TITLE                    40049
#define IDS_DESACTIVATE_SUBTITLE                40050
#define IDS_DESACTIVATE_B1                      40051
#define IDS_DESACTIVATE_B2                      40052
#define IDS_DESACTIVATE_B3                      40053
#define IDS_ERROR_MESSAGE_INI_FILE              40054
#define IDS_GENERIC_STARTING_ERROR              40055
#define IDS_MENU_UPLOADER_COMMUN                40056
#define IDS_UPLOAD_OK                           40057
#define IDS_UPLOAD_NOK                          40058
#define IDS_PROXY_OK                            40059
#define IDS_PROXY_NOK                           40060
#define IDS_MENU_SSO_NOW                        40061
#define IDS_ID2                                 40062
#define IDS_ID3                                 40063
#define IDS_ID4                                 40064
#define IDS_MENU_DUPLIQUER                      40065
#define IDS_RECOVERYSTOREPWDFAILED              40066
#define IDS_BADPWD2                             40067
#define IDS_TITRE_APPNSITES                     40068
#define IDS_MENU_CHANGER_IDS                    40069
#define IDS_CHANGER_IDS                         40070
#define IDS_MULTI_UPLOAD_OK                     40071
#define IDS_GET_ALL_CONFIGS_ERROR               40072
#define IDS_GET_ALL_CONFIGS                     40073
#define IDS_LAUNCH_APP                          40074
#define CK_MANUAL_PUT_CONFIG                    40075
#define IDS_LAUNCH_ONE_APP                      40075
#define IDS_NO_LAUNCH_PATH                      40076
#define IDS_GETCONFIGS_RESULT                   40077
#define IDS_DELETION_FORBIDDEN                  40078
#define IDS_IDANDPWDTEXT_NEW                    40079
#define IDS_IDANDPWDTITLE_NEW                   40080
#define IDS_IDANDPWDTEXT_MISSING                40081
#define IDS_IDANDPWDTITLE_MISSING               40082
#define IDS_LAUNCH_APP_ERROR                    40083
#define IDS_COMBOTYPE4                          40084
#define IDS_MENU_AJOUTER_COMPTE                 40085
#define IDS_ERROR_INI_SAV                       40086
#define IDS_ERROR_INI_RESTORED                  40087
#define IDS_ERROR_INI_NOT_RESTORED              40088
#define IDS_MENU_UPLOADER_DOMAINE               40089
#define IDS_TAB_APPLICATIONS                    40090
#define IDS_TAB_IDPWD1                          40091
#define IDS_TAB_IDPWD2                          40092
#define IDS_TAB_CONFIG1                         40093
#define IDS_TAB_CONFIG2                         40094
#define IDS_INFO_WINDOWS_SSO_MIGRATION          40095
#define IDS_ERROR_WINDOWS_SSO_MIGRATION         40096
#define IDS_ERROR_WINDOWS_SSO_LOGON             40097
#define IDS_ERROR_WINDOWS_SSO_VER               40098
#define IDS_SYNCHRO_PWD_OK                      40099
#define IDS_ERROR_WINDOWS_SSO_LOGON2            40100
#define IDS_RECOVERY_ENCRYPTED_OK               40101
#define IDS_RECOVERY_WINDOWS_OK                 40102
#define IDS_RECOVERY_ERROR                      40103
#define IDS_RECOVERY_ERROR_FORMAT               40104
#define IDS_RECOVERY_NEW_PWD                    40105
#define IDM_PWD_MENU                            40106
#define IDS_ERROR_BADRESPONSEFILE               40106
#define IDM_GENERATE_ALPHANUM_10                40107
#define IDS_PP_WINDOWS                          40107
#define IDM_GENERATE_ALPHANUM_12                40108
#define IDS_PLEASE_ENTER_WINDOWS_PASSWORD       40108
#define IDM_GENERATE_ALPHANUM_15                40109
#define IDS_MENU_CHANGEAPPPWD                   40109
#define IDM_GENERATE_ALPHANUM_20                40110
#define IDM_GENERATE_SPECIALCHARS_10            40111
#define IDM_GENERATE_SPECIALCHARS_12            40112
#define IDM_GENERATE_SPECIALCHARS_15            40113
#define IDM_GENERATE_SPECIALCHARS_20            40114
